name: check-file

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install deps
        run: |
          python3 -m pip install --upgrade pip
          pip install poetry
          make install
          pip install flake8
          pip install pytest
      - name: Run make lint
        run: make lint
      - name: Run make test
        run: make test
